### ISSUE TITLE
StartDriver() doesn't work

### ISSUE THREAD

**Issue by Andymash** [sunjerry019/nanosquared#50]
When I run the code, I find an error indicated. It happens to all the dataRay example codes, including this one, do you know what's the reason?
Traceback (most recent call last):
  File "C:\Users\yang.zeng\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\__init__.py", line 275, in __getattr__
    fixed_name = self.__map_case__[name.lower()]
KeyError: 'startdevice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yang.zeng\Documents\01.Sinaero\04.scripts\dataRay_example\dataray-python-camera-example-2021.py", line 101, in <module>
    app = MyApp()
  File "C:\Users\yang.zeng\Documents\01.Sinaero\04.scripts\dataRay_example\dataray-python-camera-example-2021.py", line 97, in __init__
    self.gd.ctrl.StartDevice()
  File "C:\Users\yang.zeng\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\__init__.py", line 277, in __getattr__
    raise AttributeError(name)
AttributeError: StartDevice

**Comment by sunjerry019** [comment]
Could you post a MWE? (or in this case, minimal, non-working, example?)

**Comment by impair-ag** [comment]
I've been in this situation as well, but I don't know how to fix it. It was successful when I first ran it, but a week later, maybe my computer automatically updated the system, and then this happened

**Comment by maxawake** [comment]
I have the same issue. I can go into devMode=False and run cam.startDevice() which returns False. Maybe its an issue with the DataRay driver

**Comment by sunjerry019** [comment]
just checking, I remember when I first started developing the code, I was also encountering some error with `StartDriver`

check https://github.com/sunjerry019/nanosquared/tree/master?tab=readme-ov-file#version-information and see if your version is newer or equal to the version of the WinCamD software listed here

a minimal code using the code in this repo would be:
```python
from nanosquared.cameras.wincamd import WinCamD

with WinCamD() as w:
    w.startDevice()
```
